### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by olezhuravlev**

### CODE REVIEW

**Comment by olezhuravlev** [comment]
Ran Plan for 2 projects:

1. dir: `.` workspace: `prod`
1. dir: `.` workspace: `stage`

### 1. dir: `.` workspace: `prod`
<details><summary>Show Output</summary>

```diff
*** CLIENT - BEFORE INIT ***


Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # yandex_resourcemanager_folder.terraform-folder-test will be created
+ resource "yandex_resourcemanager_folder" "terraform-folder-test" {
      + cloud_id    = "b1g8mq58h421raomnd64"
      + created_at  = (known after apply)
      + description = "Netology atlantis folder"
      + id          = (known after apply)
      + name        = "netology-folder-prod"
    }

Plan: 1 to add, 0 to change, 0 to destroy.


*** CLIENT - AFTER INIT ***

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -w prod`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-server:4141/lock?id=olezhuravlev%252Fterraform-cloud-test%252F.%252Fprod)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -w prod`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
### 2. dir: `.` workspace: `stage`
<details><summary>Show Output</summary>

```diff
*** CLIENT - BEFORE INIT ***


Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # yandex_resourcemanager_folder.terraform-folder-test will be created
+ resource "yandex_resourcemanager_folder" "terraform-folder-test" {
      + cloud_id    = "b1g8mq58h421raomnd64"
      + created_at  = (known after apply)
      + description = "Netology atlantis folder"
      + id          = (known after apply)
      + name        = "netology-folder-stage"
    }

Plan: 1 to add, 0 to change, 0 to destroy.


*** CLIENT - AFTER INIT ***

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -w stage`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-server:4141/lock?id=olezhuravlev%252Fterraform-cloud-test%252F.%252Fstage)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -w stage`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by olezhuravlev** [comment]
atlantis apply

**Comment by olezhuravlev** [comment]
Ran Apply for 2 projects:

1. dir: `.` workspace: `prod`
1. dir: `.` workspace: `stage`

### 1. dir: `.` workspace: `prod`
**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

---
### 2. dir: `.` workspace: `stage`
**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

---

**Review by finecon-ya-ru — APPROVED** [review]

**Comment by olezhuravlev** [comment]
atlantis apply

**Comment by olezhuravlev** [comment]
Ran Apply for 2 projects:

1. dir: `.` workspace: `stage`
1. dir: `.` workspace: `prod`

### 1. dir: `.` workspace: `stage`
**Apply Error**
```
running "/usr/local/bin/terraform apply -input=false \"/home/atlantis/.atlantis/repos/olezhuravlev/terraform-cloud-test/36/stage/stage.tfplan\"" in "/home/atlantis/.atlantis/repos/olezhuravlev/terraform-cloud-test/36/stage": exit status 1
yandex_resourcemanager_folder.terraform-folder-test: Creating...
╷
│ Error: Error while requesting API to create Folder: server-request-id = efe0da71-3faf-45a0-a6b4-cff6de8389f1 server-trace-id = 6bf1bd047f08b0f:250277be1fe340ea:6bf1bd047f08b0f:1 client-request-id = d521d52f-4c96-4f7f-a132-2d1937db6c19 client-trace-id = e7a92e46-6549-478f-89ee-2813f694dbed rpc error: code = AlreadyExists desc = Folder with name 'netology-folder-stage' already exists in cloud 'b1g8mq58h421raomnd64'
│ 
│   with yandex_resourcemanager_folder.terraform-folder-test,
│   on main.tf line 17, in resource "yandex_resourcemanager_folder" "terraform-folder-test":
│   17: resource "yandex_resourcemanager_folder" "terraform-folder-test" {
│ 
╵

```

---
### 2. dir: `.` workspace: `prod`
**Apply Error**
```
running "/usr/local/bin/terraform apply -input=false \"/home/atlantis/.atlantis/repos/olezhuravlev/terraform-cloud-test/36/prod/prod.tfplan\"" in "/home/atlantis/.atlantis/repos/olezhuravlev/terraform-cloud-test/36/prod": exit status 1
yandex_resourcemanager_folder.terraform-folder-test: Creating...
╷
│ Error: Error while requesting API to create Folder: server-request-id = e87ae942-b97b-4075-94b3-92599c18ca40 server-trace-id = c79d7adabe61d611:28a68f6e028aae4b:c79d7adabe61d611:1 client-request-id = 2c5b5d67-31c4-4368-a587-9052068fc711 client-trace-id = 453fc329-8425-47d6-91e9-af62c217e93b rpc error: code = AlreadyExists desc = Folder with name 'netology-folder-prod' already exists in cloud 'b1g8mq58h421raomnd64'
│ 
│   with yandex_resourcemanager_folder.terraform-folder-test,
│   on main.tf line 17, in resource "yandex_resourcemanager_folder" "terraform-folder-test":
│   17: resource "yandex_resourcemanager_folder" "terraform-folder-test" {
│ 
╵

```

---

**Comment by olezhuravlev** [comment]
atlantis apply

**Comment by olezhuravlev** [comment]
Ran Apply for 2 projects:

1. dir: `.` workspace: `prod`
1. dir: `.` workspace: `stage`

### 1. dir: `.` workspace: `prod`
**Apply Error**
```
running "/usr/local/bin/terraform apply -input=false \"/home/atlantis/.atlantis/repos/olezhuravlev/terraform-cloud-test/36/prod/prod.tfplan\"" in "/home/atlantis/.atlantis/repos/olezhuravlev/terraform-cloud-test/36/prod": exit status 1
╷
│ Error: Saved plan is stale
│ 
│ The given plan file can no longer be applied because the state was changed
│ by another operation after the plan was created.
╵

```

---
### 2. dir: `.` workspace: `stage`
**Apply Error**
```
running "/usr/local/bin/terraform apply -input=false \"/home/atlantis/.atlantis/repos/olezhuravlev/terraform-cloud-test/36/stage/stage.tfplan\"" in "/home/atlantis/.atlantis/repos/olezhuravlev/terraform-cloud-test/36/stage": exit status 1
╷
│ Error: Saved plan is stale
│ 
│ The given plan file can no longer be applied because the state was changed
│ by another operation after the plan was created.
╵

```

---

**Comment by olezhuravlev** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspaces: `prod`, `stage`

**Pull request closed without merging**
