### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by olezhuravlev**
New folder description introduced.

### CODE REVIEW

**Comment by olezhuravlev** [comment]
Ran Plan for 2 projects:

1. dir: `.` workspace: `prod`
1. dir: `.` workspace: `stage`

### 1. dir: `.` workspace: `prod`
<details><summary>Show Output</summary>

```diff
*** CLIENT - BEFORE INIT ***


Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # yandex_resourcemanager_folder.terraform-folder-test will be created
+ resource "yandex_resourcemanager_folder" "terraform-folder-test" {
      + cloud_id    = "b1g8mq58h421raomnd64"
      + created_at  = (known after apply)
      + description = "Netology test folder 2"
      + id          = (known after apply)
      + name        = "netology-folder-prod"
    }

Plan: 1 to add, 0 to change, 0 to destroy.


*** CLIENT - AFTER INIT ***

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -w prod`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-server:4141/lock?id=olezhuravlev%252Fterraform-cloud-test%252F.%252Fprod)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -w prod`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
### 2. dir: `.` workspace: `stage`
<details><summary>Show Output</summary>

```diff
*** CLIENT - BEFORE INIT ***


Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # yandex_resourcemanager_folder.terraform-folder-test will be created
+ resource "yandex_resourcemanager_folder" "terraform-folder-test" {
      + cloud_id    = "b1g8mq58h421raomnd64"
      + created_at  = (known after apply)
      + description = "Netology test folder 2"
      + id          = (known after apply)
      + name        = "netology-folder-stage"
    }

Plan: 1 to add, 0 to change, 0 to destroy.


*** CLIENT - AFTER INIT ***

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -w stage`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-server:4141/lock?id=olezhuravlev%252Fterraform-cloud-test%252F.%252Fstage)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -w stage`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by olezhuravlev** [comment]
atlantis plan

**Comment by olezhuravlev** [comment]
Ran Plan for 2 projects:

1. dir: `.` workspace: `stage`
1. dir: `.` workspace: `prod`

### 1. dir: `.` workspace: `stage`
<details><summary>Show Output</summary>

```diff
*** CLIENT - BEFORE INIT ***


Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # yandex_resourcemanager_folder.terraform-folder-test will be created
+ resource "yandex_resourcemanager_folder" "terraform-folder-test" {
      + cloud_id    = "b1g8mq58h421raomnd64"
      + created_at  = (known after apply)
      + description = "Netology test folder 2"
      + id          = (known after apply)
      + name        = "netology-folder-stage"
    }

Plan: 1 to add, 0 to change, 0 to destroy.


*** CLIENT - AFTER INIT ***

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -w stage`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-server:4141/lock?id=olezhuravlev%252Fterraform-cloud-test%252F.%252Fstage)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -w stage`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
### 2. dir: `.` workspace: `prod`
<details><summary>Show Output</summary>

```diff
*** CLIENT - BEFORE INIT ***


Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # yandex_resourcemanager_folder.terraform-folder-test will be created
+ resource "yandex_resourcemanager_folder" "terraform-folder-test" {
      + cloud_id    = "b1g8mq58h421raomnd64"
      + created_at  = (known after apply)
      + description = "Netology test folder 2"
      + id          = (known after apply)
      + name        = "netology-folder-prod"
    }

Plan: 1 to add, 0 to change, 0 to destroy.


*** CLIENT - AFTER INIT ***

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -w prod`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-server:4141/lock?id=olezhuravlev%252Fterraform-cloud-test%252F.%252Fprod)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -w prod`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by olezhuravlev** [comment]
atlantis apply -w stage

**Comment by olezhuravlev** [comment]
Ran Apply for dir: `.` workspace: `stage`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Comment by olezhuravlev** [comment]
atlantis apply

**Comment by olezhuravlev** [comment]
Ran Apply for 2 projects:

1. dir: `.` workspace: `prod`
1. dir: `.` workspace: `stage`

### 1. dir: `.` workspace: `prod`
**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

---
### 2. dir: `.` workspace: `stage`
**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

---

**Comment by finecon-ya-ru** [comment]
Looks good to me.

**Comment by olezhuravlev** [comment]
atlantis apply

**Comment by olezhuravlev** [comment]
Ran Apply for 2 projects:

1. dir: `.` workspace: `stage`
1. dir: `.` workspace: `prod`

### 1. dir: `.` workspace: `stage`
**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

---
### 2. dir: `.` workspace: `prod`
**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

---

**Review by finecon-ya-ru — APPROVED** [review]

**Comment by olezhuravlev** [comment]
atlantis apply

**Comment by olezhuravlev** [comment]
Ran Apply for 2 projects:

1. dir: `.` workspace: `prod`
1. dir: `.` workspace: `stage`

### 1. dir: `.` workspace: `prod`
```diff
*** SERVER - BEFORE APPLY ***

yandex_resourcemanager_folder.terraform-folder-test: Creating...
yandex_resourcemanager_folder.terraform-folder-test: Creation complete after 1s [id=b1gkta5d5u1aa7iq4407]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.


*** SERVER - AFTER APPLY ***

```

---
### 2. dir: `.` workspace: `stage`
```diff
*** SERVER - BEFORE APPLY ***

yandex_resourcemanager_folder.terraform-folder-test: Creating...
yandex_resourcemanager_folder.terraform-folder-test: Creation complete after 0s [id=b1gi9sn9fa76rrcrg9j2]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.


*** SERVER - AFTER APPLY ***

```

---

**Comment by olezhuravlev** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by olezhuravlev** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspaces: `prod`, `stage`

**Pull request merged**
